services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - lab
    ports:
      - "80:80"
    depends_on:
      - jupyterhub
      - ollama
      - chat
    restart: unless-stopped

  jupyterhub:
    image: jupyterhub/jupyterhub
    container_name: jupyterhub
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /home:/home
      - ./jupyterhub:/srv/jupyterhub
    networks:
      - lab
    expose:
      - "8000"
    restart: unless-stopped
    user: root

  ollama:
    image: ollama/ollama
    container_name: ollama
    networks:
      - lab
    expose:
      - "11434"
    volumes:
      - ollama_data:/home/ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

  chat:
    image: ghcr.io/open-webui/open-webui:main
    container_name: chat
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - WEBUI_BASE_URL=/chat/
    networks:
      - lab
    expose:
      - "8080"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  lab:
    name: lab